version: '3'
services:
  db:
    image: mongo:latest
  backend:
    image: node:latest
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    working_dir: /backend
    command: bash -c "npm install && node app.js"

  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
